### ISSUE TITLE
Instructions missing a PERL module

### ISSUE THREAD

**Issue by jrdingwall** [Downes/gRSShopper#2]
Following the install instructions this error is generated after running ".../cgi-bin/server_test.cgi" . Does not identify which PERL module is missing. 

"You are missing at least one required Perl module.

There are two ways to get your module. You can either use the 'cpan' command, or you can download the module and install it manually. We recommend you try the cpan command first.

Note that either way you must have root (system administrator) access to install the module. If you do not have access, request that your administrator make the installation for you.

To start CPAN, type:

perl -MCPAN -e shell

If this is the first time you've run CPAN, it's going to ask you a series of questions - in most cases the default answer is fine. Then, once you see the cpan> prompt, type 'install' and your module name. For example:

cpan> install LWP::UserAgent

For more information, please see: http://www.cpan.org/modules/INSTALL.html
http://www.rcbowen.com/imho/perl/modules.html "

**Comment by x28de** [comment]
Do all of your response lines such as 
`Checking for REST::Client. This proivides API Access OK` 
end with `OK` ? That would be strange.

**Comment by Downes** [comment]
I have revised server_test to make it clear which modules are missing. OK messages now green. :)
