### ISSUE TITLE
Final Step - Publishing

### ISSUE THREAD

**Issue by jrdingwall** [Downes/gRSShopper#5]
I managed to get everything sorted out and it appears to be running normally. It's the final step of the instructions that has me stuck. 

"To open the PLE, navigate to https://yourservername/cgi-bin/page.cgi?page=PLE&force=yes"

This takes me to my page which has the following on it (seems to be working as it should)

SHOWcmd = show
app = show
db = box
id = Start
title = Reader
mode =
cronsite =
context = api
format = html
action =
button =
force = no
comment =
mod_load =
table = box
Content-type: text/html
Welcome to gRSShopper

BUT the next step

"(once you publish this page you can just go to https://yourservername/ple.htm )"

When I go there I get the following

Not Found

The requested URL /ple.htm was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

I assume that that means I have not published the page. Everything seems to work, but for those new to grsshopper it might be helpful to add a more detailed instruction to publish the first page so that /ple.htm will display.

**Comment by Downes** [comment]
OK, first of all, sorry about the extra diagnostics left in the page SHOW command. These will be removed with the next upload (coming very shortly).

Your presumption is correct. You haven't yet published the PLE page. To do this:
- open the left pane (clicking on the db icon upper left)
- click 'Make' tab
- click 'List' beside Page
- click the 'Edit' icon beside the page titled 'PLE'
- click the 'Page' tab in the central pane that opens
- click the 'Publish' link 

I know, that's a lot. Publishing a page isn't something that happens a lot (pages tend to auto-publish) so it's buried a bit. That said, I should just create a 'Publish PLE' button for the welcome page. It would make things easier for new users.

**Comment by Downes** [comment]
Or even better, just have all the pages auto-publish when you first install.

**Comment by jrdingwall** [comment]
That did the trick. Thank-you very much for your help Stephen. I'm looking forward to your upcoming MOOC!
